import json
import random
from datetime import date

import pytest

from mrz_check import check_digit, parse
from mrz_check.cli import main

# Specimens from ICAO Doc 9303 (fictional "Utopia" documents).
TD3 = ["P<UTOERIKSSON<<ANNA<MARIA<<<<<<<<<<<<<<<<<<<",
       "L898902C36UTO7408122F1204159ZE184226B<<<<<10"]
TD1 = ["I<UTOD231458907<<<<<<<<<<<<<<<",
       "7408122F1204159UTO<<<<<<<<<<<6",
       "ERIKSSON<<ANNA<MARIA<<<<<<<<<<"]
TD2 = ["I<UTOERIKSSON<<ANNA<MARIA<<<<<<<<<<<",
       "D231458907UTO7408122F1204159<<<<<<<6"]
TODAY = date(2026, 9, 26)


def test_check_digit_known_values():
    assert check_digit("L898902C3") == "6"
    assert check_digit("740812") == "2"
    assert check_digit("120415") == "9"
    assert check_digit("D23145890") == "7"


def test_td3_specimen():
    r = parse(TD3, today=TODAY)
    assert r.valid and r.format == "TD3"
    assert (r.surname, r.given_names) == ("ERIKSSON", "ANNA MARIA")
    assert (r.document_number, r.issuing_country, r.nationality, r.sex) == ("L898902C3", "UTO", "UTO", "F")
    assert r.birth_date == date(1974, 8, 12) and r.expiry_date == date(2012, 4, 15)
    assert r.optional_data == "ZE184226B"
    assert r.is_expired(TODAY) is True


def test_td1_specimen():
    r = parse(TD1, today=TODAY)
    assert r.valid and r.format == "TD1" and r.document_number == "D23145890"
    assert (r.surname, r.given_names) == ("ERIKSSON", "ANNA MARIA")


def test_td2_specimen():
    r = parse(TD2, today=TODAY)
    assert r.valid and r.format == "TD2" and r.document_number == "D23145890"


def test_whitespace_and_lowercase_are_normalized():
    assert parse("  " + TD3[0].lower() + " \n\n " + TD3[1] + "  ", today=TODAY).valid


@pytest.mark.parametrize("pos,field", [(9, "document_number"), (19, "birth_date"), (27, "expiry_date"),
                                       (42, "personal_number"), (43, "composite")])
def test_wrong_check_digit_is_flagged(pos, field):
    l2 = TD3[1]
    bad = l2[:pos] + str((int(l2[pos]) + 1) % 10) + l2[pos + 1:]
    r = parse([TD3[0], bad], today=TODAY)
    assert not r.valid
    # Field check digits are themselves covered by the composite check digit, so both must fail.
    assert {c.field for c in r.checks if not c.ok} == {field, "composite"}


def test_every_single_digit_substitution_is_detected():
    """7-3-1 weights are coprime with 10, so changing any one digit must break a check."""
    l2 = TD3[1]
    for i, c in enumerate(l2):
        if not c.isdigit():
            continue
        for d in "0123456789":
            if d != c:
                assert not parse([TD3[0], l2[:i] + d + l2[i + 1:]], today=TODAY).valid, (i, d)


def test_invalid_date_and_layout():
    l2 = TD3[1].replace("7408122", "7413312")  # month 13
    l2 = l2[:13] + "741331" + check_digit("741331") + l2[20:]
    r = parse([TD3[0], l2], today=TODAY)
    assert "birth date is not a valid date" in r.errors and not r.valid
    with pytest.raises(ValueError):
        parse(["P<UTO", "123"])


def test_td1_long_document_number():
    number = "D23145890123"  # 12 characters: 9 in place, 3 + check digit in optional data
    l1 = "I<UTO" + number[:9] + "<" + (number[9:] + check_digit(number)).ljust(15, "<")
    l2 = "7408122F1204159UTO<<<<<<<<<<<"
    l2 += check_digit(l1[5:30] + l2[0:7] + l2[8:15] + l2[18:29])
    r = parse([l1, l2, TD1[2]], today=TODAY)
    assert r.valid and r.document_number == number


def test_cross_check_against_mrz_library():
    """Random TD3 codes generated by an independent implementation must validate here, and vice versa."""
    gen = pytest.importorskip("mrz.generator.td3")
    rng = random.Random(9303)
    letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    for _ in range(300):
        number = "".join(rng.choice(letters + "0123456789") for _ in range(9))
        code = gen.TD3CodeGenerator(
            "P", "UTO", "".join(rng.choice(letters) for _ in range(8)), "".join(rng.choice(letters) for _ in range(6)),
            number, "UTO", f"{rng.randint(50, 99):02d}{rng.randint(1, 12):02d}{rng.randint(1, 28):02d}",
            rng.choice("MF"), f"{rng.randint(27, 39):02d}{rng.randint(1, 12):02d}{rng.randint(1, 28):02d}",
            "".join(rng.choice(letters + "0123456789") for _ in range(rng.randint(0, 14))))
        r = parse(str(code), today=TODAY)
        assert r.valid, str(code)
        assert r.document_number == number and r.is_expired(TODAY) is False


def test_cli(capsys):
    assert main(TD3) == 0
    assert "VALID" in capsys.readouterr().out
    assert main([TD3[0], TD3[1][:-1] + "9"]) == 1
    assert "INVALID" in capsys.readouterr().out
    assert main(["--json", *TD1]) == 0
    assert json.loads(capsys.readouterr().out)["valid"] is True
    assert main(["short"]) == 2


def test_td2_long_document_number():
    number = "D2314589012"  # 11 characters
    l2 = number[:9] + "<" + "UTO" + "7408122F1204159" + (number[9:] + check_digit(number)).ljust(7, "<")
    l2 += check_digit(l2[0:10] + l2[13:20] + l2[21:35])
    r = parse([TD2[0], l2], today=TODAY)
    assert r.valid and r.document_number == number
